### LMN-3 DrumConfigGenerator Configuration ###
# path: 
#   - path to the drum kits
# use_subfolders: 
#   - if true, multiple drum kits in subfolders are expected
#   - if false, only one drum kit in the specified path is expected
# note_range: 
#   - notes in this range are populated with remaining files, which were not used in the mapping
# mappings: 
#   - mapping for each note to a specific file
#   note_number: 
#     - number of the note
#   file_name_regex: 
#     - if the regex is found somewhere in a file name, the corresponding file is mapped to that note
#     - if multiple files are matching the given regex, the alphabetically first file is used. The remaining files, which matched the regex, are mapped to the following notes.
### 

path: "DrumKits"
use_subfolders: true
note_range:
  first_note: 46
  last_note: 69
mappings:
  - note_number: 46
    file_name_regex: "_BD"
  - note_number: 48
    file_name_regex: "_SN"
  - note_number: 54
    file_name_regex: "_HH"
  - note_number: 51
    file_name_regex: "_CP"
  - note_number: 56
    file_name_regex: "_OH"
  - note_number: 59
    file_name_regex: "_RD"
  - note_number: 61
    file_name_regex: "_CR"